### ISSUE TITLE
Failing test: felt252_to_bool_bug

### ISSUE THREAD

**Issue by igaray** [lambdaclass/cairo_native#290] opened 2023-08-11 12:28 UTC
Failing program:

```
use array::ArrayTrait;

        fn felt_to_bool(x: felt252) -> bool {
            x == 1
        }

        fn run_test(a: felt252) -> bool {
            felt_to_bool(a)
        }
```
with input `1` when comparing to cairo-vm output

Test can be found in `tests/boolean.rs felt252_to_bool_bug` 

comparing a felt252 == 1 will lead to wrong results

**Comment by azteca1998** [comment] 2023-08-17 15:53
Running the code without `--canonicalize` works, therefore it's not a bug in our codebase, but rather in MLIR's. The canonicalization should always yield equivalent code, which is not the case in this bug.

I've opened an issue in the LLVM project: https://github.com/llvm/llvm-project/issues/64774

**Comment by edg-l** [comment] 2023-12-14 16:11
According to the linked pr this is fixed in a future llvm version already.

**Closed** 2024-05-22 17:04 UTC
Labels: bug
