### ISSUE TITLE
Refactor poseidon libfuncs to use the BlockExt trait

### ISSUE THREAD

**Issue by edg-l** [lambdaclass/cairo_native#530] opened 2024-04-18 10:16 UTC
See: https://github.com/lambdaclass/cairo_native/pull/518

Refactor the code implementing the libfuncs to use the trait methods from `BlockExt`.

**Comment by Saraahma** [comment] 2024-04-18 10:23
hi  learn web 3

**Comment by Saraahma** [comment] 2024-04-18 10:23
hi

**Comment by Saraahma** [comment] 2024-04-18 10:23
hello

**Comment by princeibs** [comment] 2024-04-18 10:31
Can I hop on this?  @edg-l

**Comment by edg-l** [comment] 2024-04-18 10:33
> Can I hop on this? @edg-l

Sure! assigned

**Comment by princeibs** [comment] 2024-04-18 10:45
Alright. For the main time, I will just get myself familiar with the codebase while waiting for the PR to be merged

**Comment by edisontim** [comment] 2024-05-10 14:08
Gm @princeibs are you still working on this?

**Comment by TropicalDog17** [comment] 2024-05-23 05:17
Hi @edg-l @igaray could I work on this issue? Thanks!

**Comment by adrianvrj** [comment] 2024-05-23 11:03
Hi, is this still available? I am pretty sure I can work on this and deliver it fast! :)

**Comment by PhantomOz** [comment] 2024-05-24 00:10
Hello @edg-l and @igaray, I am a smart contract developer and I can execute this task if it is still available.

**Comment by RajeshRk18** [comment] 2024-05-27 09:09
Hey, I don't know if the issue is assigned to the order of comments. But, I've experience doing the refactoring. Shall I take up this?

**Comment by od-hunter** [comment] 2024-05-31 20:41
Can I be assigned this issue, this is my first time contributing and I’d love to be given the opportunity.

**Closed** 2024-06-18 13:52 UTC
Labels: good first issue, libfuncs, odhack, difficulty-easy
