### ISSUE TITLE
Replay Error: expected 'LIMIT_DIRECTION', got 'Result::unwrap failed'

### ISSUE THREAD

**Issue by JulianGCalderon** [lambdaclass/cairo_native#797] opened 2024-09-16 21:32 UTC
Executing transaction [0x4e443d4da181e740e08221c2b1258b3a52e20e803df13d858ebe19b002222cd](https://starkscan.co/tx/0x04e443d4da181e740e08221c2b1258b3a52e20e803df13d858ebe19b002222cd) with Native returns `Result::unwrap failed` instead of the expected error `LIMIT_DIRECTION`.

- Native Full Error: `Transaction execution has failed:\n0: Error in the called contract (contract address: 0x054e2640fe5633aa21d431405f8539a72fcfd85d968de02c3e65478c93f8045f, class hash: 0x05400e90f7e0ae78bd02c77cd75527280470e2fe19c54970dd79dc37a9d3645c, selector: 0x015d40a3d6ca2ac30f4031e42be28da9b056fef9bb7357ac5e85627ee876e5ad):\nNative execution error: Result::unwrap failed.\n`
- VM Full Error: `Transaction execution has failed:\n0: Error in the called contract (contract address: 0x054e2640fe5633aa21d431405f8539a72fcfd85d968de02c3e65478c93f8045f, class hash: 0x05400e90f7e0ae78bd02c77cd75527280470e2fe19c54970dd79dc37a9d3645c, selector: 0x015d40a3d6ca2ac30f4031e42be28da9b056fef9bb7357ac5e85627ee876e5ad):\nError at pc=0:4573:\nCairo traceback (most recent call last):\nUnknown location (pc=0:67)\nUnknown location (pc=0:1835)\nUnknown location (pc=0:2478)\nUnknown location (pc=0:3255)\nUnknown location (pc=0:3795)\n\n1: Error in the called contract (contract address: 0x0707bfb1bcaa5492e4d95b6d06f67fa6f7c585d31499f3e951701d002ef7f2a5, class hash: 0x07fb70339df89a45968717ecfbb778d8d55c5072e3eb70a4e90a027858b3d99e, selector: 0x0041a2bd7b071429bead2df8961ad96d60151bdd19b77adf82ac2ac78a2a0024):\nError at pc=0:6408:\nCairo traceback (most recent call last):\nUnknown location (pc=0:263)\nUnknown location (pc=0:3294)\n\n2: Error in the called contract (contract address: 0x02ed66297d146ecd91595c3174da61c1397e8b7fcecf25d423b1ba6717b0ece9, class hash: 0x07b5cd6a6949cc1730f89d795f2442f6ab431ea6c9a5be00685d50f97433c5eb, selector: 0x015543c3708653cda9d418b4ccd3be11368e40636c10c44b18cfe756b6d88b29):\nError at pc=0:15:\nCairo traceback (most recent call last):\nUnknown location (pc=0:307)\nUnknown location (pc=0:293)\n\n3: Error in a library call (contract address: 0x02ed66297d146ecd91595c3174da61c1397e8b7fcecf25d423b1ba6717b0ece9, class hash: 0x02b39bc3f4c1fd5bef8b7d21504c44e0da59cf27b350551b13d913da52e40d3b, selector: 0x015543c3708653cda9d418b4ccd3be11368e40636c10c44b18cfe756b6d88b29):\nError at pc=0:166:\nCairo traceback (most recent call last):\nUnknown location (pc=0:3937)\nUnknown location (pc=0:3663)\nUnknown location (pc=0:1806)\n\n4: Error in the called contract (contract address: 0x0707bfb1bcaa5492e4d95b6d06f67fa6f7c585d31499f3e951701d002ef7f2a5, class hash: 0x07fb70339df89a45968717ecfbb778d8d55c5072e3eb70a4e90a027858b3d99e, selector: 0x03fd64ee153df97d0e33c89b6a777a91001a7ebe785ace3aba25812fd45c3766):\nError at pc=0:11078:\nCairo traceback (most recent call last):\nUnknown location (pc=0:1372)\nUnknown location (pc=0:3936)\nUnknown location (pc=0:7874)\nUnknown location (pc=0:7874)\nUnknown location (pc=0:8070)\nUnknown location (pc=0:10809)\n\n5: Error in the called contract (contract address: 0x00000005dd3d2f4429af886cd1a3b08289dbcea99a294197e9eb43b0e0325b4b, class hash: 0x030e64ecb769ff832478ed5ce52fc5b81ffc7d32dd36cd9b8937135683339a2c, selector: 0x0168652c307c1e813ca11cfb3a601f1cf3b22452021a5052d8b05f1f1f8a3e92):\nError at pc=0:23456:\nCairo traceback (most recent call last):\nUnknown location (pc=0:3541)\nUnknown location (pc=0:11789)\n\n6: Error in the called contract (contract address: 0x0707bfb1bcaa5492e4d95b6d06f67fa6f7c585d31499f3e951701d002ef7f2a5, class hash: 0x07fb70339df89a45968717ecfbb778d8d55c5072e3eb70a4e90a027858b3d99e, selector: 0x0399c6d7581cbb37d2e578d3097bfdd3323e05447f1fd7670b6c3a3fb9d9ff79):\nError at pc=0:8876:\nCairo traceback (most recent call last):\nUnknown location (pc=0:2167)\nUnknown location (pc=0:4511)\n\n7: Error in the called contract (contract address: 0x00000005dd3d2f4429af886cd1a3b08289dbcea99a294197e9eb43b0e0325b4b, class hash: 0x030e64ecb769ff832478ed5ce52fc5b81ffc7d32dd36cd9b8937135683339a2c, selector: 0x015543c3708653cda9d418b4ccd3be11368e40636c10c44b18cfe756b6d88b29):\nExecution failed. Failure reason: 0x4c494d49545f444952454354494f4e ('LIMIT_DIRECTION').\n`

**Comment by edg-l** [comment] 2024-09-20 08:54
Status:

Same thing as native happens with sierra-emu, this may be a quirk in the syscall handler implementation for native since sierra-emu uses the same one?

**Comment by edg-l** [comment] 2024-09-20 11:54
Looks like with native at one point gets to that error, but continues one more execution, receiving a contract address of 0 though

```
==== CALLER: ContractAddress(PatriciaKey(0x54e2640fe5633aa21d431405f8539a72fcfd85d968de02c3e65478c93f8045f)) ====
==== CLASH Some(ClassHash(0x7fb70339df89a45968717ecfbb778d8d55c5072e3eb70a4e90a027858b3d99e)) ====
==== CODE ADDRESS Some(ContractAddress(PatriciaKey(0x707bfb1bcaa5492e4d95b6d06f67fa6f7c585d31499f3e951701d002ef7f2a5))) ====
==== CALLDATA Calldata([0x4, 0x0, 0x2ed66297d146ecd91595c3174da61c1397e8b7fcecf25d423b1ba6717b0ece9, 0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7, 0x0, 0x0, 0x307a0e5bc03dc6, 0x0, 0x1, 0x5900cfa2b50d53b097cb305d54e249e31f24f881885aae5639b0cd6af4ed298, 0x68f5c6a61780768455de69077e07e89787839bf8166decfbf92b645209c0fb8, 0x0, 0x0, 0x1dfe311, 0x0, 0x2, 0x5dd3d2f4429af886cd1a3b08289dbcea99a294197e9eb43b0e0325b4b, 0x53c91253bc9682c04929ca02ed00b3e423f6710d2ee7e0d5ebb06f3ecf368a8, 0x68f5c6a61780768455de69077e07e89787839bf8166decfbf92b645209c0fb8, 0x14f8b588e368f1000000000000000, 0x14, 0x0, 0x1dfe311, 0x0, 0x1, 0xfff4e1298a7b5da5a0ab63e1f8b36c0b, 0x0, 0x0, 0x2, 0x5dd3d2f4429af886cd1a3b08289dbcea99a294197e9eb43b0e0325b4b, 0x4718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d, 0x53c91253bc9682c04929ca02ed00b3e423f6710d2ee7e0d5ebb06f3ecf368a8, 0x20c49ba5e353f80000000000000000, 0x3e8, 0x0, 0x1e00a4e, 0x0, 0x1, 0xa5ce67cea180d3e9295dcac71bb, 0x0, 0x0, 0x4766b63d996280000, 0x0]) ====
==== ENTRYPOINT EntryPointSelector(0x41a2bd7b071429bead2df8961ad96d60151bdd19b77adf82ac2ac78a2a0024) ====
==== ERROR ====
NativeExecutionError { info: "Error at pc=0:15:\nGot an exception while executing a hint: Error at pc=0:166:\nGot an exception while executing a hint: Native execution error: Native execution error: Native execution error: Native execution error: LIMIT_DIRECTION\nCairo traceback (most recent call last):\nUnknown location (pc=0:3937)\nUnknown location (pc=0:3663)\nUnknown location (pc=0:1806)\n\nCairo traceback (most recent call last):\nUnknown location (pc=0:307)\nUnknown location (pc=0:293)\n" }


==== CALLER: ContractAddress(PatriciaKey(0x0)) ====
==== CLASH Some(ClassHash(0x5400e90f7e0ae78bd02c77cd75527280470e2fe19c54970dd79dc37a9d3645c)) ====
==== CODE ADDRESS None ====
==== CALLDATA Calldata([0x1, 0x707bfb1bcaa5492e4d95b6d06f67fa6f7c585d31499f3e951701d002ef7f2a5, 0x41a2bd7b071429bead2df8961ad96d60151bdd19b77adf82ac2ac78a2a0024, 0x2b, 0x4, 0x0, 0x2ed66297d146ecd91595c3174da61c1397e8b7fcecf25d423b1ba6717b0ece9, 0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7, 0x0, 0x0, 0x307a0e5bc03dc6, 0x0, 0x1, 0x5900cfa2b50d53b097cb305d54e249e31f24f881885aae5639b0cd6af4ed298, 0x68f5c6a61780768455de69077e07e89787839bf8166decfbf92b645209c0fb8, 0x0, 0x0, 0x1dfe311, 0x0, 0x2, 0x5dd3d2f4429af886cd1a3b08289dbcea99a294197e9eb43b0e0325b4b, 0x53c91253bc9682c04929ca02ed00b3e423f6710d2ee7e0d5ebb06f3ecf368a8, 0x68f5c6a61780768455de69077e07e89787839bf8166decfbf92b645209c0fb8, 0x14f8b588e368f1000000000000000, 0x14, 0x0, 0x1dfe311, 0x0, 0x1, 0xfff4e1298a7b5da5a0ab63e1f8b36c0b, 0x0, 0x0, 0x2, 0x5dd3d2f4429af886cd1a3b08289dbcea99a294197e9eb43b0e0325b4b, 0x4718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d, 0x53c91253bc9682c04929ca02ed00b3e423f6710d2ee7e0d5ebb06f3ecf368a8, 0x20c49ba5e353f80000000000000000, 0x3e8, 0x0, 0x1e00a4e, 0x0, 0x1, 0xa5ce67cea180d3e9295dcac71bb, 0x0, 0x0, 0x4766b63d996280000, 0x0]) ====
==== ENTRYPOINT EntryPointSelector(0x15d40a3d6ca2ac30f4031e42be28da9b056fef9bb7357ac5e85627ee876e5ad) ====
==== ERROR ====
NativeExecutionError { info: "Result::unwrap failed." }
```

**Comment by edg-l** [comment] 2024-10-10 10:50
Fixed on latest main

```
2024-10-10T10:50:26.340193Z  INFO replay: execution finished successfully, transaction_hash: "0x04e443d4da181e740e08221c2b1258b3a52e20e803df13d858ebe19b002222cd", chain: "mainnet", execution_status: "REVERTED", rpc_execution_status: "REVERTED", execution_error_message: "Transaction execution has failed:\n0: Error in the called contract (contract address: 0x054e2640fe5633aa21d431405f8539a72fcfd85d968de02c3e65478c93f8045f, class hash: 0x05400e90f7e0ae78bd02c77cd75527280470e2fe19c54970dd79dc37a9d3645c, selector: 0x015d40a3d6ca2ac30f4031e42be28da9b056fef9bb7357ac5e85627ee876e5ad):\nNative execution error: Result::unwrap failed.\n", n_events_and_messages: "{ events_number: 1, l2_to_l1_messages_number: 0 }", rpc_n_events_and_msgs: "{ events_number: 1, l2_to_l1_messages_number: 0 }", da_gas: "{ l1_da_gas: 128, l1_gas: 0 }", state_changes_for_fee_str: "{ n_class_hash_updates: 0, n_compiled_class_hash_updates: 0, n_modified_contracts: 1, n_storage_updates: 1 }"
    at replay/src/main.rs:356
    in replay::transaction with hash: "0x04e443d4da181e740e08221c2b1258b3a52e20e803df13d858ebe19b002222cd", chain: "mainnet"
```

**Comment by edg-l** [comment] 2024-10-10 11:01
Edit: The unwrap is still there, but i think this is not a bug, but rather how a call contract handles the called contract returning an error, in the vm case i think it returns a generic error stating the contract class hash and info and on the native side we return the retdata of the called contract https://github.com/lambdaclass/sequencer/blob/d0c9daed20e1d434b01037eeab67761e737977a4/crates/blockifier/src/execution/native/syscall_handler.rs#L564

**Comment by pefontana** [comment] 2024-10-30 17:09
Fixed

**Closed by pefontana** 2024-10-30 17:09 UTC
