### ISSUE TITLE
Pending AOT issues and bugs

### ISSUE THREAD

**Issue by azteca1998** [lambdaclass/cairo_native#404] opened 2023-12-21 15:25 UTC
Some tests started failing after the AOT refactor:
  - ~~`libfuncs::stark_net::test::storage_base_address_from_felt252`: The bug seems to originate from within LLVM itself. It used to work before since it's passing on main.~~
  - ~~`bit_array` on alexandria started failing too with a gas mismatch by about 10 million. Again, it worked on main but not on this PR.~~
  - Optimization levels other than `-O0` are failing with either garbage data or segmentation faults.

**Comment by edg-l** [comment] 2024-01-05 13:20
https://github.com/lambdaclass/cairo_native/blob/21d421bcd71a8b70f6e9ab4d137ad5f849833909/tests/common.rs#L248

i changed this to Agressive and the tests passed regardless

**Comment by edg-l** [comment] 2024-01-05 14:26
Running the benches doesnt seem to break either. On x86

**Comment by igaray** [comment] 2024-01-11 14:37
Seems to be not reproducible at the momento so closing for now.

**Closed by igaray** 2024-01-11 14:37 UTC
Labels: bug
